name: Build Artifact

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder to enable action in branch
        run: true
